baseurl = "http://rockhopper.dk/"
languageCode = "en-us"
title = "Rockhopper.dk"
newContentEditor = "nvim"
theme = "rockhopper"

[params]
  Author = "Henrik Farre"
  GoogleAnalyticsUserID = "UA-4186065-1"
  stylesheets = ["styles.css", "magnific-popup/magnific-popup.css", "custom.css"]
  javascripts = ["magnific-popup/jquery.magnific-popup.js", "rockhopper.js"]

# [taxonomies]
#   tag = "Tags"
#   category = "Categories"

[[menu.main]]
    name = "About me"
    pre = "<i class='fa fa-user'></i>"
    identifier = "About me"
    weight = -120
    url = "/about-me"

[[menu.main]]
    name = "Github"
    pre = "<i class='fa fa-github'></i>"
    identifier = "Github"
    weight = -110
    url = "https://github.com/henrik-farre"

[[menu.main]]
    name = "LinkedIn"
    pre = "<i class='fa fa-linkedin'></i>"
    identifier = "LinkedIn"
    weight = -100
    url = "https://dk.linkedin.com/in/henrikfarre"
