baseurl = "https://henrik-farre.github.io/"
languageCode = "en-us"
title = "Rockhopper.dk"
pygmentsstyle = "vim"
pygmentsuseclasses = true

[params]
  author = "Henrik Farre"
  GitHub = "henrik-farre"
  GoogleAnalyticsUserID = "UA-4186065-1"
  stylesheets = ["styles.css", "magnific-popup/magnific-popup.css", "custom.css"]
  javascripts = ["magnific-popup/jquery.magnific-popup.js", "rockhopper.js"]
